name: servana
description: "A new Flutter project."

# لمنع النشر العرضي على pub.dev
publish_to: 'none'

# إعدادات الإصدار (لاندرويد وآي أو إس)
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # حزم أيقونات وأدوات واجهة المستخدم
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1

  # حزم الموقع والخرائط
  geolocator: ^13.0.2
  geocoding: ^3.0.0


  # حزم إدخال البيانات
  intl_phone_field: ^3.2.0

  # حزم الصلاحيات والتخزين المحلي
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^8.0.0

  # التعريب
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.1

  # أخرى
  http: ^1.4.0
  url_launcher: ^6.3.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4  # مطلوب لتوليد ملفات التعريب

flutter:
  generate: true  # تمكين توليد ملفات l10n تلقائياً
  uses-material-design: true

  assets:
    - assets/images/
