// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJWvmNo_KnaYbH3yaBfsNzr-tXsveSF4',
    appId: '1:15565102567:web:69f167484c1f1f6f79b142',
    messagingSenderId: '15565102567',
    projectId: 'servana-ab0e5',
    authDomain: 'servana-ab0e5.firebaseapp.com',
    storageBucket: 'servana-ab0e5.firebasestorage.app',
    measurementId: 'G-FR11QBXV7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43xfOpR2wSHfEjN3TZ9VC9PbkMOMUwck',
    appId: '1:15565102567:android:717d088b3ed5d35579b142',
    messagingSenderId: '15565102567',
    projectId: 'servana-ab0e5',
    storageBucket: 'servana-ab0e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYUSpcI_U6uSzbvUIJEe1zreWdLMmO8Y',
    appId: '1:15565102567:ios:680dc02b764531a779b142',
    messagingSenderId: '15565102567',
    projectId: 'servana-ab0e5',
    storageBucket: 'servana-ab0e5.firebasestorage.app',
    iosBundleId: 'com.example.servana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxYUSpcI_U6uSzbvUIJEe1zreWdLMmO8Y',
    appId: '1:15565102567:ios:680dc02b764531a779b142',
    messagingSenderId: '15565102567',
    projectId: 'servana-ab0e5',
    storageBucket: 'servana-ab0e5.firebasestorage.app',
    iosBundleId: 'com.example.servana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyJWvmNo_KnaYbH3yaBfsNzr-tXsveSF4',
    appId: '1:15565102567:web:94bc3aa7dab35e3d79b142',
    messagingSenderId: '15565102567',
    projectId: 'servana-ab0e5',
    authDomain: 'servana-ab0e5.firebaseapp.com',
    storageBucket: 'servana-ab0e5.firebasestorage.app',
    measurementId: 'G-FLD76C5HQ3',
  );
}
